version: "3"

services:
  front:
    container_name: Frontend
    build:
      context: ./Frontend
    stdin_open: true
    ports:
      - "3000:3000"
    networks:
      - telorespaldoapp
    volumes:
      - ./Frontend:/usr/src/app
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  back:
    container_name: Backend
    build:
      context: ./Backend
    ports:
      - "3001:3001"
    links:
      - mongo
    depends_on:
      - mongo
      - front
    networks:
      - telorespaldoapp
    volumes:
      - ./Backend:/usr/src/app
    command: npm run start:dev
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  mongo:
    container_name: MongoDatabase
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - telorespaldoapp
    volumes:
      - mongo-data:/data/db
      - ./MongoDB/configdb:/data/configdb
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M

networks:
  telorespaldoapp:
    driver: bridge

volumes:
  mongo-data:
    driver: local
