# Generated by Django 4.2.11 on 2024-04-26 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inf236backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=256)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='motor',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='motor',
            name='tipo',
            field=models.CharField(default='Desconocido', max_length=256),
        ),
        migrations.CreateModel(
            name='Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='Desconocido', max_length=256)),
                ('fecha_de_asignacion', models.DateField()),
                ('estado', models.BooleanField(default=False)),
                ('id_camion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inf236backend.camion')),
                ('id_motor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inf236backend.motor')),
            ],
        ),
    ]
