# Generated by Django 4.2.11 on 2024-04-29 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inf236backend', '0002_camion_motor_estado_motor_tipo_asignacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Componentes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=256)),
                ('nombre', models.CharField(max_length=256)),
                ('estado', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='JefeDeMotores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=256)),
                ('nombre', models.CharField(max_length=256)),
                ('turno', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Mecanico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=256)),
                ('nombre', models.CharField(max_length=256)),
                ('estado', models.BooleanField(default=False)),
                ('turno', models.CharField(max_length=256)),
            ],
        ),
    ]
