# Generated by Django 4.2.11 on 2024-06-06 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inf236backend', '0003_componentes_jefedemotores_mecanico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignacion',
            name='fecha_de_asignacion',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='camion',
            name='patente',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='jefedemotores',
            name='rut',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='mecanico',
            name='rut',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='motor',
            name='n_serie',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
