# Generated by Django 4.2.11 on 2024-06-11 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inf236backend', '0004_alter_asignacion_fecha_de_asignacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delete_Asignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(default='Desconocido', max_length=40)),
                ('fecha_de_asignacion', models.DateTimeField()),
                ('estado', models.BooleanField(default=False)),
                ('id_motor', models.CharField(max_length=10)),
                ('id_camion', models.CharField(max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delete_Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(max_length=40)),
                ('estado', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Delete_Motor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('n_serie', models.CharField(max_length=40)),
                ('estado', models.BooleanField(default=False)),
                ('tipo', models.CharField(default='Desconocido', max_length=40)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='camion',
            name='patente',
            field=models.CharField(error_messages={'unique': 'Ya existe una Camion con esta patente'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='jefedemotores',
            name='rut',
            field=models.CharField(error_messages={'unique': 'Ya existe un JefeDeMotores con este rut'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='mecanico',
            name='rut',
            field=models.CharField(error_messages={'unique': 'Ya existe un Mecanico con este rut'}, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='motor',
            name='n_serie',
            field=models.CharField(error_messages={'unique': 'Ya existe un motor con este número de serie.'}, max_length=100, unique=True),
        ),
    ]
